AWSTemplateFormatVersion: 2010-09-09
Description: RDS

Parameters: 
 NameBase: 
  Type: String
  Default: lecture10

Resources: 
  # サブネットグループ作成
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: For RDS
      DBSubnetGroupName: !Sub ${NameBase}-DBSubnetGroup
      SubnetIds:
      - !ImportValue ap-northeast-1a-PrivateSubnet1-ID
      - !ImportValue ap-northeast-1c-PrivateSubnet2-ID
      Tags:
      - Key: Name
        Value: !Sub ${NameBase}-DBSubnetGroup

 # RDSインスタンス作成
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceIdentifier: rdsdbinstance
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: "{{resolve:secretsmanager:lecture:SecretString:password}}"
      DeletionProtection: false
      DeleteAutomatedBackups: true
      DBInstanceClass: db.t3.micro
      VPCSecurityGroups:
        - Ref: DBSecurityGroup
      AvailabilityZone: 
        Fn::Select: 
        - 0
        - Fn::GetAZs: ""
      Port: 3306
      MultiAZ: false
      DBSubnetGroupName: !Ref RDSSubnetGroup

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue VPC-ID
      GroupDescription: for RDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue EC2SecurityGroup-ID
